# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-10 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_college_major', models.CharField(blank=True, max_length=60, null=True)),
                ('realname', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenantid', models.AutoField(primary_key=True, serialize=False)),
                ('tenantcategory', models.SmallIntegerField(choices=[(1, '公益类'), (2, '体育类'), (3, '公共传媒类'), (4, '艺术类'), (5, '科技类'), (6, '兴趣爱好类'), (7, '职业拓展类')], default=1)),
                ('tenantname', models.CharField(max_length=45, verbose_name='社团名称')),
                ('tenantbelong', models.CharField(blank=True, max_length=20, null=True, verbose_name='所属单位')),
                ('tenantcampus', models.CharField(blank=True, max_length=20, null=True, verbose_name='所属校区')),
                ('tenantintroduction', models.TextField(max_length=200, verbose_name='社团简介')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
