# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-10 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenantbelong',
            field=models.CharField(max_length=20, verbose_name='所属单位'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenantcampus',
            field=models.CharField(max_length=20, verbose_name='所属校区'),
        ),
    ]
